services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  traffic_generator:
    build:
      context: ./traffic-generator
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - CACHE_URI=http://cache:5000/cache

  cache:
    build:
      context: ./cache
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379

volumes:
  es_data: