services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

volumes:
  mongo_data:
